### ISSUE TITLE
Correctly handling hash in links

### ISSUE THREAD

**Issue by petard** [krasimir/navigo#117]
I'm using Navigo to route and load views from the back-end when the user clicks on a menu in my SPA and the route is resolved. When using ```<a href="/<view>" data-navigo><viewName></a>``` in the menu links everything works fine, with or without hash in the URL, e.g. `/<view>` and `/#/<view>` are interchangeable.

What is the correct way to enable deep-linking in my current app so when users bookmark the page they are present with the right view? The current URL `/<view>` is not a valid page on the server as all navigation is handled by Navigo. When adding a hash in the menu link like ```<a href="/#/<view>" data-navigo><viewName></a>``` routing isn't working anymore even if routes are update accordingly.

**Comment by krasimir** [comment]
Hm ... the hash based routing should work. You just have to initialize the router with that option:
```js
var router = new Navigo(null, true);
```

Otherwise if you want to use the History API of the browser you need to:
* update your server to forward all the request to your index file
* make sure that you set a proper `root` while initializing Navigo

The process is explained [here](http://krasimirtsonev.com/blog/article/deep-dive-into-client-side-routing-navigo-pushstate-hash#client-side-routing-is-not-exactly-only-client-side).

**Comment by petard** [comment]
Thanks, that did the trick!
