### ISSUE TITLE
[BUG] - Regexp pages

### ISSUE THREAD

**Issue by petrck** [krasimir/navigo#149]
Hi, from version 5.x.x stop working regexp in router definitions. I have the same regexp as in version 4.7.x and it stop work. Is problem in my code, I found no reason in changelog. 

Here is my routes:

```
...
.on(/\/[^/]+\/([a-zA-Z0-9-]+)/, {
    as: "cms.page",
    uses: (urlId) => {
      b.init(() => {
        return CmsModule.IndexAction({router: router, urlId: urlId, active: `/${urlId}`});
      })
    }
  }).on("/", {
    as: "home.index",
    uses: () => {     
      b.init(() => {      
        return HomeModule.IndexAction({router: router, active: "/"});
      });
    }
  ...
  });
```

The cms.page never get handle. I tested it with your examples on readme and the same problem.
Is something wrong in my code and readme is not updated or this is bug..?

Thank you.

**Comment by krasimir** [comment]
@petrck can you please post the URL which should match. I mean what's in the browser's address bar which should match the regexp.

**Comment by petrck** [comment]
Sure. Maybe this is problem in my code, but older version really works well. Simply I need this:

HOME: http://localhost:5000
CMS http://localhost:5000/everytihing

Now I see, regexp is not fully actually, but this is only on slash different at start. 

For example here is test my actually expression:
https://regex101.com/r/dWfp70/2/tests

Thank you for your help.

**Comment by krasimir** [comment]
So, version `5.0.0` introduced a breaking change in the way of how Navigo handles the regexp. That's why in that version we bumped the major number from 4 to 5. Unfortunately you have to amend your regexp to make it work. 

If you want to catch everything why not using just `([a-zA-Z0-9-]+)`. I'm a little bit confused in your initial regexp example `/\/[^/]+\/([a-zA-Z0-9-]+)/`.

**Comment by petrck** [comment]
Confused? But why. I think unit test in previous post is fully clear. I Need to create two groups, host + start with slash (/everything) is second group. This `([a-zA-Z0-9-]+)` will not really solve. Please look again to unit test and returning string with group. 

Here is link to this regexp: https://stackoverflow.com/questions/43831198/javascript-pretty-url-regular-expresison

Instand of "/everything", I have `[a-zA-Z0-9-]
`
But if new version cannot support this way, I will stay at older version. No problem.

Thank you.

**Comment by krasimir** [comment]
I'm probably really dumb but still can't quite understand where is the bug. If you come with a failing test I'll probably be able to resolve it. Otherwise I guess you should stick with version 4.

**Comment by petrck** [comment]
I'm not sure, what you mean failing tests. Both tests passed, otherwise I would not send them. In attachment is screen, that test are passed.
<img width="685" alt="snimek obrazovky 2017-08-12 v 14 47 05" src="https://user-images.githubusercontent.com/9294613/29240828-2bbf6ab6-7f6d-11e7-8000-398de6241609.png">

Did you have wrong language selected? I hope that the intention is now clearer.
Thank you

**Comment by krasimir** [comment]
No I mean a Navigo unit test failing. I'm sure that the regexp is fine and it matches what you meant. I want to see it failing in a Navigo test so I can see where the bug happens in Navigo's source code.

**Comment by krasimir** [comment]
Looking at the OP I think the problem was in the way of how the routes are defined. I don't remember having such api where we have a path/regexp and then an object map. However, the new 8.0.0 will support regexp. There are couple of unit tests on that functionality and also an example here https://github.com/krasimir/navigo/tree/big-rewrite/examples/regexp. So I'm closing this one.
