### ISSUE TITLE
[BUG?] Before hook

### ISSUE THREAD

**Issue by neo85** [krasimir/navigo#150]
Hi, 
not sure if this is a bug or a feature. I call Window.confirm method in before hook. When the user presses cancel i call done(false). The handler is not resolved , that is ok but the hash will change anyway.
I do not want the hash to change when i call done(false), is that possible?
thx

**Comment by krasimir** [comment]
The thing is that once you call `.navigate` Navigo changes the URL and then runs the hooks. Even tho this sounds wrong it makes sense because without resolving the URL we have no idea which hook to execute. I'll suggest to put your `window.confirm` outside of the hook and just guard the `.navigate` call.
