### ISSUE TITLE
Pausing, navigating and resuming resolves the route

### ISSUE THREAD

**Issue by mbucurcf** [krasimir/navigo#172]
Pausing the router, navigating and then resuming resolves the route, because it resumes before the listener callback (`_onLocationChange`) is executed.

The workaround I have used is to resume with a delay.

```
router.pause();
router.navigate(some_route);
setTimeout(function () {
    router.resume();
}, 500);
```

**Comment by krasimir** [comment]
Thanks for reporting. I'll see what I can do.

**Comment by mathiasrw** [comment]
Any news on this one?

**Comment by 7ender13** [comment]
Same issue for me, any news ?

**Comment by krasimir** [comment]
Hey,

I'm working on a complete rewrite of the library because the code code is not really manageable. Once its done I'll address all the issues in that new release. Some of the old issues could be solved in the current version. However, this one leads to lots of changes and I decided to leave for that new release.

**Comment by 7ender13** [comment]
Hey,

Good to ear ! Good luck for the rewrite ;)

**Comment by mathiasrw** [comment]
@krasimir sounds awesome - put it up into a new branch if you need help with anything.

**Comment by YoavHortman** [comment]
Is there an update on this issue?

**Comment by krasimir** [comment]
Hey,

the new version 8.0.0 is here. In that new version there is no pausing and resuming. The same functionality is now available as part of the `navigate` method. You're basically saying "Go there but don't resolve any of my routes".

```js
router.navigate('/foo/bar', { shouldResolve: false });
```

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.

**Comment by richturner** [comment]
Hey, great project. Just migrating to 8.0.0 and needed to replace pause/resume as mentioned in the change logs. Noticed that the typescript definition for NavigateOptions doesn't contain shouldResolve.

**Comment by krasimir** [comment]
@richturner yes, sorry. The API changed a bit and there are a couple of other flags that give you more control on what exactly happens when a route is resolved. I'll suggest to check this section of the documentation https://github.com/krasimir/navigo/blob/master/DOCUMENTATION.md#navigating-between-routes.
