### ISSUE TITLE
Passing Hidden Params

### ISSUE THREAD

**Issue by elrapha** [krasimir/navigo#184]
Does this library support passing hidden parameters among pages on navigate? I thought it would be useful to pass params that do no necessarily appear in the url or query string. Similar to the generic way of POSTing data to a page in the traditional sense.

router.navigate(url,absoluteFlag,hiddenParam).

**Comment by krasimir** [comment]
First of all sorry for the delayed answer.

I started implementing this feature and the implementation flooded the code base with a lot of patches to make this possible. Then I realized that it is not the job of the router to deal with such state. So I have to start thinking in a more pragmatic way and try minimazing the API of the library. I'll say that if some data need to be send to a handler you have to:

* Use [partial application](https://medium.com/javascript-scene/curry-or-partial-application-8150044c78b8) if the data is static
* Store it in the app's state and fetch it when the new page loads (handler gets executed).

P.S.
sorry for pushing back but Navigo became like a little frankenstein because I was trying to solve every single feature request. To make to stable we have to focus only on the routing.
