### ISSUE TITLE
Routes not resolved when only query params updated.

### ISSUE THREAD

**Issue by nmfoss** [krasimir/navigo#188]
I dont know if this might be an issue or a feature request.

If I only update query params the routes are not triggered.

Example:
router.navigate(?something)

This only updates the URL in the addressfield, but does not trigger the default route. I am trying to do navigation with only updating the URL params so I dont need a lot of useless url handling on the serverside. Using a switch case on the query.

**Comment by gabrielchiconi** [comment]
Hi! Not the author, but I used to do barehanded routing before coming across Navigo (which is exactly why I found this), and I believe it is not possible since to track the routes we need to listen to 'hashchange' (or fall back to polling location.hash), both of which only work when the # bit changes. Does updating the hash location together with the query string force a refresh and get the desired result?

**Comment by krasimir** [comment]
With the latest 8.0.0 you can I think achieve what you want. For example the following:

```js
const router = new Navigo("/");
router..on((match) => {
  console.log(match);
})
setTimeout(() => {
  router.navigate("/?foo=bar");
}, 5000);
```

Updates the page URL to just `/?foo=bar` and the route is resolved. I see the console.log.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
