### ISSUE TITLE
Click on same link several time

### ISSUE THREAD

**Issue by adoweb** [krasimir/navigo#198]
Hallo Krasimir, thank you so match for this awseome plugin.

I use Navigo to open my modal links. I noticed that if I click twice on the same link, for the second time modal window does not open. I think this issue it's related with the latest resolved route. 
How do I do that every time when I click on the modal link Navigo should triggerd my modal function.

E.g.
    Router.on({
        'about/:name': function(params) {
            var url = '/api/' + Language.current + '/pages/' + params.name;
            showModalContent('#page-modal, url);
         }
    })

**Comment by krasimir** [comment]
The way of how this should work is that you have a dedicated URL for the modal but when you close it you change the URL back. Like for example:

```
/about/team
--> click the link and show the modal
/about/team/modal
---> you close the modal
/about/team
---> if you click the link again it will work because the URL is again just /about/team
```

**Comment by dpsifr** [comment]
I actually need the link to execute my code every time it is clicked to refresh the content. Is there a way to force this behavior?

**Comment by jbmulligan** [comment]
I have run into this same issue in a slightly different context.  I have a page that renders differently based on query parameters.  When I call navigate with everything the same except for the query params, the route handler does not fire, I guess because it thinks it is already there so there is nothing to do.  Clearly one solution would be to change the URL structure, moving the query parameters into route elements.  Is there any other solution?

**Comment by krasimir** [comment]
So there are a couple of things here.

@adoweb and @dpsifr: if you are going to rely on Navigo for logic you HAVE TO change the URL to get your handler called again. That's kinda the idea of the Web isn't it? To have different content of the different URLs. So I'm still suggesting to change the URL when you close the modal.

@jbmulligan in the latest version 8.0.0 this problem is solved. You may `navigate` to the same URL but with different query (GET) params and the handler is getting called for each one of them because this is a different URL for Navigo.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.

**Comment by jbmulligan** [comment]
Thanks for the update!
Oddly, the behavior that you describe (handler re-called when query params
are changed) already seems to occur in version 7.1.2 that I am running.

Thanks again for your work and for sharing this very useful piece of
software!
-Jeff
