### ISSUE TITLE
Event binding in templates

### ISSUE THREAD

**Issue by bennettscience** [krasimir/navigo#203]
I'm newer to routing and I understand the mechanisms of single-page apps, updating container `div` content with templates, etc.

I'm having a hard time binding events (click, keyup) to templated elements. If the script is loaded in the `index` container, there is no element to bind and it throws an error. I feel like I'm missing something fundamental, but I can't put my finger on it.

The main script is expecting a promise returned from a Firebase user object...could that be causing the problem?

**Comment by byrro** [comment]
Hi @bennettscience 

I believe your issue is not associated directly with a question, problem or bug in Navigo, is it? I guess you'd receive more help if you post on StackOverflow or similar community of developers.

If your issue is indeed associated specificaly with Navigo implementation, please clarify in more details more what have you tried (providing your code), what you do you expect and what's going wrong.

Hope that helps you in overcoming the problem quicker.

**Comment by krasimir** [comment]
@byrro thank you for popping in here.
@bennettscience I agree with @byrro. If you can provide some code that relates to Navigo we'll get a better context and will probably be able to answer. I'll close this issue for now. Please send a comment if you still need assistance.
