### ISSUE TITLE
notFound is not working on new page (refresh)

### ISSUE THREAD

**Issue by FaBeyyy** [krasimir/navigo#229]
Example: 
```js 
this.router
            .on({
            '/': (query) => new HomeView(hc, query),
            '/product-selector': () => new ProductSelectorView(hc),

        })
            .notFound(function (query) { console.log('404'); hc.innerHTML= '<div>404</div>'});
```
Also tried having the home component to an empty route like in the example but didnt work either.
Everytime i manually go to an invalid url it still fallbacks to the homeview instead of triggering the notfound handler

**Comment by krasimir** [comment]
This is now fixed in the version 8.0.0. Example here https://github.com/krasimir/navigo/tree/big-rewrite/examples/229

The code looks like this and the not-found handler is called properly:
```html
<div>
  <a href="/" data-navigo>Home</a>
  <a href="/product-selector" data-navigo>Product selector</a>
  <a href="/dsaljkdksajfkasjkdsa" data-navigo>Not found</a>
</div>
<hr />
<div id="content"></div>
<script src="/navigo.js"></script>
<script>
  window.addEventListener("load", () => {
    const router = new Navigo("/");
    const render = (content) =>
      (document.querySelector("#content").innerHTML = content);

    router
      .on({
        "/": (match) => {
          render("home");
        },
        "/product-selector": (match) => {
          render("Product selector");
        },
      })
      .notFound(() => {
        render("Not found");
      })
      .resolve();
  });
</script>
```

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
