### ISSUE TITLE
Typescript Support Broken

### ISSUE THREAD

**Issue by chrisalexander55** [krasimir/navigo#234]
OS: OSX, 10.14.2 
Node.js@10.15.0
NPM@6.7.0
Typescript@3.2.2
Navigo@7.1.2
Type Definition File: @types/navigo@7.0.1

`import Navigo from "navigo;`
Error: cannot find module 'navigo'

It appears that the type definition file is not >= ES2015 module compliant.
From index.d.ts:
`
export = Navigo;
export as namespace Navigo;
`

There is an open ticket on SO where the author also faced this issue but appears to have not submitted an issue.

https://stackoverflow.com/questions/54314816/i-cant-use-or-import-navigo-in-typescript

Thank you in advance for your assistance.

**Comment by youjenli** [comment]
I have faced this issue, too!
After a few hours of researching, I found that we can import Navigo with `import Navigo = require('navigo');`.

The reason that we have to import Navigo with this syntax is because of the way which Navigo exported itself.  
Navigo was exported in the form of UMD. And the way which was chosen to export Navigo to commonjs module loader is to replace the export object with the constructor function of Navigo.  
Therefore, the author of @types/navigo have to export Navigo with `export = Navigo`, the syntax which was designed to import commonjs module in TypeScript.  
That is why we can't import this package with modern ES6 syntax.

**Comment by milesje** [comment]
Any movement on this issue... I just started a new LitElement project in TypeScript and would like to use Navigo, but not being able to import it into my TypeScript file is a bit of a hindrance.

**Comment by krasimir** [comment]
Hey @chrisalexander55, @youjenli and @milesje,

Navigo got rewritten in TypeScript and the current version 8.0.0 is in beta. Could be installed via `npm install navigo@beta` and the types are bundled inside the library. Everything with typescript should be ok if you use that version.

![Screenshot 2020-12-29 at 10 08 08](https://user-images.githubusercontent.com/528677/103269164-e3893a00-49bd-11eb-8ea8-f01049d82891.png)

I know it's a major release so you may need to read the migration guide https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide or the new documentation https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
