### ISSUE TITLE
Calling done(false) in before hook still updates route

### ISSUE THREAD

**Issue by rcrisp** [krasimir/navigo#243]
If you call done(false) in a before hook, the URL still updates to the requested page.  If you then try to navigate to the requested page later either programmatically or by clicking a link, it does not work because the router believes it is already on that page.  My expected behavior was calling done(false) should not update the page URL.

**Comment by weisborg** [comment]
Just got on to report this very issue.  Documentation shows it as a way to abort going to a page, but the browser history and the internal resolved route in Navigo both think it went there.  I tried using the leave hook by defining individual .on handlers (since it can't be defined as a global hook), and it fires before the resolution takes place.  I didn't see a way to abort the leave though, so all it can do is grab the previous resolved route.  It can be used in before to navigate back then, but the browser history has even more entries now.  And, to do it you have to pause and then resume the router to not change the page.  The flow for that doesn't work well either since resume fires too soon and I have to put it in a settimeout or something to queue it so it doesn't get events and trigger a resolve anyway.

I ended up scraping it and going back to my multiple paths in one .on with a global before hook.  I call history.back() along with the done(false) call to at least clear up the browser history.  I also need a longer timeout of about 1-2 seconds for the resume call since a hash change event fires later than the handling of a .navigate call.

I'm still stuck though since the internal resolved URL thinks it went to that page already, so aborting a page load means I can't go back to that page without going to another.

**Comment by krasimir** [comment]
The problem describe here is fixed in the latest version 8.0.0. Can you @rcrisp @weisborg try it out.

Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.

P.S.S
I'm trying to start fresh on the new version 8.0.0. If you try it and still doesn't work let me know and I'll reopen the issue.
