### ISSUE TITLE
File not found error.

### ISSUE THREAD

**Issue by Miltex** [krasimir/navigo#247]
In the console the following error is shown:

![image](https://user-images.githubusercontent.com/3899343/81624676-2d8cc380-93cd-11ea-8645-225cc519ba24.png)

How should this file (navigo.min.js.map) be generated?

I tried to use this file (https://github.com/krasimir/navigo/blob/master/lib/navigo.min.js.map)

But the following error occurs: 
         navigo.min.js.map uncaught syntaxerror: unexpected token ':'

**Comment by krasimir** [comment]
This must be a problem with the build setup. There is a new version 8.0.0 where this problem is gone. 

Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.

P.S.S
I'm trying to start fresh on the new version 8.0.0. If you try it and still doesn't work let me know and I'll reopen the issue.
