### ISSUE TITLE
Ghpages and Navigo. Redirect to index.html on accessing subpath.

### ISSUE THREAD

**Issue by Blakeinstein** [krasimir/navigo#278]
Accessing a subroute directly, returns to the 404.html. How can you redirect from 404.html to index.html?

**Comment by krasimir** [comment]
GitHub pages does not allow you to control the routing. In order to have Navigo working you need to amend the http routing and point all the requests to a single html file. With GitHub pages this is not possible. The only workaround that comes to my mind is to generate all the pages as static files and those files to have the same content. But even then the 404 page may not be properly handled.

**Comment by Blakeinstein** [comment]
I was going through projects using this package, and found this workaround.

https://github.com/rafgraph/spa-github-pages

On the 404 page, it converts the sub route, to a query which is executed on index.html itself. Effectively redirecting properly. I would suggest, adding this to the readme for future reference.
