### ISSUE TITLE
Route handler executing before URL is updated

### ISSUE THREAD

**Issue by waynebaylor** [krasimir/navigo#279]
Using v8.9.1

For example:
 
```javascript
router.on("/home", () => {
  console.log(router.getCurrentLocation());
});
```

I was expecting this to log the `Match` for `/home`, but it doesn't. The `Match` returned by `getCurrentLocation()` is the *previous* one. It appears that the URL (and thus `getCurrentLocation()`) are updated after the handler is executed.

**Comment by krasimir** [comment]
Hey @waynebaylor,

this is done on purpose. The updating of the actual URL in the browser happens at the very end because in Navigo the routes may have hooks and in those hooks you may decide to not call the handler or to call the handler but don't update the URL. There are such edge cases. At this point is not a good to change this behavior.

It's a bit weird to me that you are not using the `match` object passed to the handler:
```
router.on("/home", (match) => {
  console.log(match);
});
```
It's basically the same thing except that it probably contains what you want.

**Comment by waynebaylor** [comment]
I've been using navigo 7.x and I have a component that checks if the user is authenticated and redirects to the login screen if necessary. Of course, there are some public screens where I don't want to do this and I've been checking the URL to make that decision. After upgrading to 8.x this logic doesn't work anymore because the URL is now being updated after the component renders. 

It's fine if this has changed in the newer version, it just felt odd that the URL didn't reflect the route that was currently being rendered.

**Comment by krasimir** [comment]
@waynebaylor but you can still access the new URL if you use the `match` object as I hint above:

```
router.on("/home", (match) => {
  console.log(match.url); // <-- url here is showing you the matching address
});
```
