### ISSUE TITLE
Problem getting History API to work

### ISSUE THREAD

**Issue by zirafa** [krasimir/navigo#5]
Thanks for this library. I am able to get hash based routes working but cannot get clean URLs to work on my localhost. I added the Apache .htaccess routing as described in http://krasimirtsonev.com/blog/article/deep-dive-into-client-side-routing-navigo-pushstate-hash but does not seem to work. 

Also tried setting the "root" value when creating a new Navigo() instance but not sure what that argument should actually look like, i.e. http://localhost, localhost/index.html, etc

**Comment by krasimir** [comment]
> Also tried setting the "root" value when creating a new Navigo() instance but not sure what that argument should actually look like, i.e. http://localhost, localhost/index.html, etc
If your `index.html` stays in `localhost/index.html` then it should be `http://localhost`. If it's under `localhost/project/app/index.html` then you should use `http://localhost/project/app`.

Can you please post the content of your `.htaccess` file. This one may be tricky. It's difficult to advice you because the mod_rewrite module may be configured differently on your machine. It really depends  of your OS. Is the apache part of some other app like MAMP for example.

In order to get the History API working you need to receive the `index.html` every time when you request  the specific URL. Even if you use additional subfolders that don't exist. You should always end up using the same `index.html`. Some of the results [here](https://www.google.bg/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=apache%20point%20every%20request%20to%20index.html&oq=apache%20point%20every%20request%20to%20index.html&aqs=chrome..69i57.7247j0j1) may help you.

**Comment by zirafa** [comment]
Thanks...here is my .htaccess and some example routes. It seems like it works fine for a single level route but as soon as there is a second level in the route it fails. This happens for me on local MAMP environment as well as a shared server environment.

```
<ifModule mod_rewrite.c>
  Options +FollowSymLinks
  IndexIgnore */*
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule (.*) index.html
</ifModule>
```

```
    var router = new Navigo();
    router.on({
      'firstlevel/:secondlevel': function (params) {
          alert('fails');
       },
       'firstlevel': function() {
          alert('works');
       },
       'one/two': function() {
          alert('fails');
       }         
    })
```

Additionally, I get an odd error in my browser - a white screen and in the console I see these errors for all my js assets (as if it is trying to access the JS file from within the subfolder...) which seems to indicate a server/apache problem.
```
Uncaught SyntaxError: Unexpected token <
```

**Comment by krasimir** [comment]
The error that you are getting is due to the fact that the browser is opening your index.html file in the places where a javascript is expected. For me it looks that the server forwarding is not configured properly. Can you please do the [following](http://stackoverflow.com/questions/7670561/how-to-get-htaccess-to-work-on-mamp):
> Go to httpd.conf on /Applications/MAMP/conf/apache and see if the LoadModule rewrite_module modules/mod_rewrite.so line is un-commented (without the # at the beginning)

**Comment by zirafa** [comment]
I believe I figured out the issue - rewrite_module was turned on, but my site was installed in a subdirectory of the site root directory. In my index.html file all js & css is referenced via relative URLs. Setting the <base href="/subdir/" /> in <head> solves the issue. I noticed in your [demo](https://github.com/krasimir/navigo/blob/master/demo/index.php) you are setting all of your paths as absolute paths which also solves it. 

Links that explain the issue:
- http://stackoverflow.com/questions/1755826/mod-rewrite-path-issues
- http://stackoverflow.com/questions/25293601/angularjs-crashes-when-i-define-a-route-with-two-parameters-in-it

**Comment by krasimir** [comment]
Ah right. I forgot to mention that the assets paths should be absolute ones.
