### ISSUE TITLE
Any differences between Navigo and other routers?

### ISSUE THREAD

**Issue by Mevrael** [krasimir/navigo#51]
For example, there is an older and smaller in size vanilla router [page.js](https://github.com/visionmedia/page.js).

What whas the main reason you created another router?
Have you analyzed how Navigo is different/better/worse then other router libraries?

Nevertheless, nice work and your ES6 syntax and export is very appreciated in my build process.

**Comment by krasimir** [comment]
Well, everything started as a simple helper which was literally 50 loc. Then later I decided to form a library because people were visiting [this](http://krasimirtsonev.com/blog/article/A-modern-JavaScript-router-in-100-lines-history-api-pushState-hash-url) blog posts and asking if there is a npm module. Not sure if it is better comparing the other alternatives. It was just fitting in my use case.
