### ISSUE TITLE
Add a feature

### ISSUE THREAD

**Issue by cloudever** [krasimir/navigo#54]
Hi. I'd like to make a suggestion about the feature.
Following steps are for an imagination of workflow.
1. Imagine, page now on the root '/'. 
2. Click to open MENU, then page will navigate to '#/menu'
3. Make an action to close menu and the page will return back to '/'
4. Click to open CART, then the page will navigate to '#/cart'.
But if I'll click 2 times back in the browser, it will navigate to '#/menu' and open it by handling browser history!
Are there some possible features to **ignore history item** but handle it?
I tried to use **pause** API function, but it works like no changes.
Thanks.

**Comment by betofigueiredo** [comment]
Can you use **history.go(-1)** to close MENU?

**Comment by krasimir** [comment]
@cloudever this seems a little bit hacky. I'll not change how the browser handles route because probably the users get used to it. Do you mean that you want to trigger a route handler but don't change the URL so the user don't get the address bar updated?

**Comment by cloudever** [comment]
@betofigueiredo , I tried to use history.back(), but it won't done my job.
@krasimir no, I just would like to replace history. I've played with location.href and I think it's possible to use _location.replace_ instead of _location.href =_

**Comment by cloudever** [comment]
@krasimir I just want to make possible close menu and cart on mobile phone by clicking back button.
But all routes write to history and it will being negative UX.

**Comment by krasimir** [comment]
Heu @cloudever,

I made some experiments and now I think that Navigo can't fix the problem. That's because we are trying to use the URL as a state holder for the menu and at the same time a state holder for the page management. From a application point of view that's wrong. The state of the different parts of the application should be handled separately. I see your use case but I'll suggest to handle the menu opening and closing using cookies and leave the pagination to the router.

**Comment by carloslfu** [comment]
@cloudever I guess you are looking for something like [adressbar](https://github.com/cerebral/addressbar) you can use it with Navigo. Hope it helps.
